### ISSUE TITLE
Difference in node and java while connecting to S/4

### ISSUE THREAD

**Issue by pranavnagpalr** [SAP-samples/cloud-cap-samples-java#11]
Hi,

With the odata connection branch, I see that it works different to how nodejs connects to S/4HANA. package.json should be used to setup destinations, whereas I dont see this in the current branch. The annotation that is used to get the HTTP destination is also not readily available in documentations. 
ConditionalOnProperty("cds.services.abp.destination"). How does this behave? How is it getting the destination

Thanks

**Comment by beckermarc** [comment]
Hi,

OData service consumption is not yet supported out-of-the-box in Java. The branch shows how this can be done in custom code, while already using the APIs that we will also use later on.
The `ConditionalOnProperty` annotation is a [Spring annotation](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/condition/ConditionalOnProperty.html) that ensures that the Spring bean (here: the event handler) is only loaded in case the property is available. The destination property is defined in the [application.yaml](https://github.com/SAP-samples/cloud-cap-samples-java/blob/odata-service-consumption/srv/src/main/resources/application.yaml#L31).

As this feature is not supported end-to-end by CAP Java you don't find any details of this in the documentation. Also the `odata-consumption` branch should be treated as "preview" or "experimental".

**Comment by pranavnagpalr** [comment]
Thank you for your quick response. Yes, I noted that ConditionalOnProperty but I was not able to figure out how the destination is being loaded. It would be great to have feature parity in future. I will try to deploy this and see if it runs with my S/4 on premise. 
Thanks 
Pranav

**Comment by mofterdinger** [comment]
@pranavnagpalr Hi, we close this support channel and replace it with our [community](https://answers.sap.com/tags/9f13aee1-834c-4105-8e43-ee442775e5ce). If you need further support, use this support channel and open questions.

Thanks,
Markus
