### ISSUE TITLE
Connecting Remote Rest service hosted in External Cloud

### ISSUE THREAD

**Issue by nehasuman92** [SAP-samples/cloud-cap-samples-java#148]
Hello Team,

We need to connect our CAP java based application to External cloud services rest APIs
 Can we call An external rest API from CAP odata service. If it is possible can you please guide me here.

**Comment by beckermarc** [comment]
Hi @nehasuman92,

the issue tracker on this repository is intended for issues with the CAP Java sample application in this repository.
Please refer to the following places to get information about how to get support on your own CAP projects:
- https://github.com/SAP-samples/cloud-cap-samples-java#get-support
- https://cap.cloud.sap/docs/resources/

I am therefore closing this issue.

Best regards,
Marc
