### ISSUE TITLE
How to create a java module in CAP Project

### ISSUE THREAD

**Issue by nehasuman92** [SAP-samples/cloud-cap-samples-java#149]
Hello Team,

I am using SAP BTP trial account and create on CAP project from template it has create db, srv and app folder. But it has not created pom file, and java project structure inside srv.  Could you please let us know how to add the proper srv module with pom file , package.json file etc. in the CAP project. 

Is there a way for creating please help me.
Thanks in advance, eagerly waiting for reply

**Comment by beckermarc** [comment]
Hi @nehasuman92,

the issue tracker on this repository is intended for issues with the CAP Java sample application in this repository.
Please refer to the following places to get information about how to get support on your own CAP projects:
- https://github.com/SAP-samples/cloud-cap-samples-java#get-support
- https://cap.cloud.sap/docs/resources/

I am therefore closing this issue.

Best regards,
Marc
