### ISSUE TITLE
Unable to open the page after subscription, several errors occurred.

### ISSUE THREAD

**Issue by thetruechar** [SAP-samples/cloud-cap-samples-java#202]
code: https://github.tools.sap/golden-path-playground/wjr-java-sample/tree/kyma-mtx-approuter

After deploying an application with Approuter and multitenancy with service-manager in Kyma, the consumer account (GPC2) was able to successfully subscribe the app. However, when attempting to access the application, several 404 errors occurred, making it hard to understand what was wrong. Could you please review the issue? I have added you to the GitHub organization and BTP subaccount.

<img width="1868" alt="image" src="https://user-images.githubusercontent.com/9455827/218299124-9b31df40-c0cf-459d-b607-41e0d2cfd8cf.png">
<img width="945" alt="image" src="https://user-images.githubusercontent.com/9455827/218299587-6be7dd43-a95c-4036-b125-86d47304c3d3.png">

**Comment by sidakphull** [comment]
I am getting somewhat similar error while deploying Single Tenant version of CF:

<img width="1512" alt="Screenshot 2023-02-13 at 9 37 35 AM" src="https://user-images.githubusercontent.com/112457741/218368608-bb97abd0-9156-4bc3-82dd-9dc50b0ba987.png">

@beckermarc

**Comment by beckermarc** [comment]
Yes, seems like the latest UI Version is breaking our UI. You could pin the version to a specific one in: https://github.com/SAP-samples/cloud-cap-samples-java/blob/main/app/fiori.html#L66-L67
I will look into how to fix these issues.

**Comment by beckermarc** [comment]
UI issues should be solved with https://github.com/SAP-samples/cloud-cap-samples-java/pull/204

**Comment by beckermarc** [comment]
Please retry with the latest version in `main`
