### ISSUE TITLE
helm install failing - expects service-manager with parameters

### ISSUE THREAD

**Issue by kaundinyaekta** [SAP-samples/cloud-cap-samples-java#220]
Hi,

While deploying the multitenant app to kyma, helm install fails with the following error:
Error: INSTALLATION FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
service-manager:
- (root): serviceOfferingName is required
- (root): servicePlanName is required

service-manager was removed from values.yaml as instructed here https://github.com/SAP-samples/cloud-cap-samples-java#multi-tenant

Could you please help with this?

Thanks,
Ekta Sharma

**Comment by sidakphull** [comment]
Hi @kaundinyaekta ,

Some instructions were missing. PR #222  has them. 

Thanks,
Sidak
