### ISSUE TITLE
Mtx-sidecar service manager cannot deploy the tables to hana hdi

### ISSUE THREAD

**Issue by zc11818** [SAP-samples/cloud-cap-samples-java#229]
Hi Team, 
I encountered a problem when attempting to deploy the CAP service to SAP Business Technology Platform, Kyma Runtime. Specifically, I encountered an issue with the HANA HDI deployment while deploying a multi-tenant application to the Kyma cluster. I followed the instructions provided in the readme file, and everything seemed to be going well except for the HANA HDI deployment, which ultimately failed. To investigate further, I reviewed the log of the bookshop-sidecar pod, and the error log is displayed below:

[mtx] - ------------[BEGIN HDI-DEPLOY-OUTPUT]---------------
[cds] - GET /-/cds/jobs/pollJob(ID='ac5a5fcc-xxxxxxxxxxxxxxxxxxx')
[deploy] - Using HDI deployer from /layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/hdi-deploy/library.js
[cds] - GET /-/cds/jobs/pollJob(ID='ac5a5fcc-xxxxxxxxxxxxxxxxxxxx')
[deploy] - Deployment to container 9122Cxxxxxxxxxxxxxxxxxxxxxxxxxx failed - error: HDI make failed [Deployment ID: none].
[deploy] - Error: HDI make failed
[mtx] - -------------[END HDI-DEPLOY-OUTPUT]----------------
[mtx] - Error: HDI deployment failed with exit code 1
at /layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/bin/deploy/to-hana/hdiDeployUtil.js:142:35
at ChildProcess.<anonymous> (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/hdi-deploy/library.js:102:14)
at ChildProcess.emit (node:events:513:28)
at maybeClose (node:internal/child_process:1100:16)
at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
at Process.callbackTrampoline (node:internal/async_hooks:130:17)

I think the mtx-sidecar cannot find the db files in the gen folder. How could I inspect this problem ? 

Thanks & Regards.

**Comment by beckermarc** [comment]
Can you please attach slightly more log context (ideally the whole output) from the bookshop-sidecar pod? This will help in analyzing the issue. Thanks!

**Comment by zc11818** [comment]
Please find the log info as below: 

[cds] - loaded model from 1 file(s):
[2m
srv/csn.json
[0m
[cds] - connect to db > hana {
clientid: 'sb-005e4886-c17e-40de-a501-e97b0bb168f4!b10057|service-manager!b3',
clientsecret: '...',
sm_url: 'https://service-manager.cfapps.us21.hana.ondemand.com',
url: 'https://pdp-kylin-dev.authentication.us21.hana.ondemand.com',
xsappname: '005e4886-c17e-40de-a501-e97b0bb168f4!b10057|service-manager!b3'
}
[cds] - serving cds.xt.ModelProviderService { path: '/-/cds/model-provider' }
[cds] - serving cds.xt.DeploymentService { path: '/-/cds/deployment' }
[cds] - serving cds.xt.SaasProvisioningService { path: '/-/cds/saas-provisioning' }
[cds] - serving cds.xt.ExtensibilityService { path: '/-/cds/extensibility' }
[cds] - serving cds.xt.JobsService { path: '/-/cds/jobs' }
[mtx] - creating HDI container for tenant t0
[pool] - effective pool configuration: {
min: 0,
max: 100,
testOnBorrow: true,
fifo: false,
acquireTimeoutMillis: 1000,
softIdleTimeoutMillis: 30000,
idleTimeoutMillis: 30000,
evictionRunIntervalMillis: 60000,
numTestsPerEvictionRun: 34
}
[cds] - loaded model from 1 file(s):
[2m
../layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds-mtxs/db/t0.cds
[0m
[mtx] - ------------[BEGIN HDI-DEPLOY-OUTPUT]---------------
[deploy] - Using HDI deployer from /layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/hdi-deploy/library.js
[mtx] - -------------[END HDI-DEPLOY-OUTPUT]----------------
[mtx] - successfully finished HANA deployment for tenant t0
[cds] - server listening on { url: 'http://localhost:8080' }
[cds] - launched at 5/25/2023, 2:35:33 AM, version: 6.6.2, in: 22.888s
[cds] - POST /-/cds/model-provider/getCsn
[cds] - POST /-/cds/model-provider/getCsn
[cds] - POST /-/cds/model-provider/getCsn
[cds] - PUT /-/cds/saas-provisioning/tenant/c04c3de2-32dd-4991-a2ca-0f3874d402c0
[mtx] - enqueuing 'subscribe' job for [ Set(1) { 'c04c3de2-32dd-4991-a2ca-0f3874d402c0' } ] with args [
{
subscriptionAppId: 'bookshopsaas!t10057',
subscriptionAppName: 'bookshopsaas',
subscribedTenantId: 'c04c3de2-32dd-4991-a2ca-0f3874d402c0',
subscribedZoneId: 'c04c3de2-32dd-4991-a2ca-0f3874d402c0',
subscribedLicenseType: 'DEVELOPER',
subscribedCrmId: null,
subscribedSubdomain: 'pdp-kylin-dev-consume',
subscribedSubaccountId: 'c04c3de2-32dd-4991-a2ca-0f3874d402c0',
subscriptionAppPlan: null,
subscriptionAppAmount: null,
dependentServiceInstanceAppIds: null,
dependantServiceInstanceAppIds: null,
eventType: 'CREATE',
globalAccountGUID: '6691d385-cab0-4ff1-997c-d6bcc9438559',
additionalInformation: { clientid: null, clientsecret: null, tokenurl: null },
userId: 'jiedong.yu@sap.com',
userInfo: {
userId: 'jiedong.yu@sap.com',
userName: 'jiedong.yu@sap.com',
email: 'jiedong.yu@sap.com',
subIdp: 'I332359',
sub: '2640a191-e5b8-4089-8884-e7b5a5f72ba7'
},
_applicationUrlFromJava_: null
}
]
[cds] - GET /-/cds/jobs/pollJob(ID='ac5a5fcc-3e7d-4336-a7b2-2ab1225e6941')
[mtx] - creating HDI container for tenant c04c3de2-32dd-4991-a2ca-0f3874d402c0
[cds] - GET /-/cds/jobs/pollJob(ID='ac5a5fcc-3e7d-4336-a7b2-2ab1225e6941')
[cds] - GET /-/cds/jobs/pollJob(ID='ac5a5fcc-3e7d-4336-a7b2-2ab1225e6941')
[mtx] - ------------[BEGIN HDI-DEPLOY-OUTPUT]---------------
[cds] - GET /-/cds/jobs/pollJob(ID='ac5a5fcc-3e7d-4336-a7b2-2ab1225e6941')
[deploy] - Using HDI deployer from /layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/hdi-deploy/library.js
[cds] - GET /-/cds/jobs/pollJob(ID='ac5a5fcc-3e7d-4336-a7b2-2ab1225e6941')
[deploy] - Deployment to container 9122C0D1D7344645881DFB1CBC5E0F58 failed - error: HDI make failed [Deployment ID: none].
[deploy] - Error: HDI make failed
[mtx] - -------------[END HDI-DEPLOY-OUTPUT]----------------
[mtx] - Error: HDI deployment failed with exit code 1
at /layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/bin/deploy/to-hana/hdiDeployUtil.js:142:35
at ChildProcess.<anonymous> (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/hdi-deploy/library.js:102:14)
at ChildProcess.emit (node:events:513:28)
at maybeClose (node:internal/child_process:1100:16)
at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
at Process.callbackTrampoline (node:internal/async_hooks:130:17)
[cds] - GET /-/cds/jobs/pollJob(ID='ac5a5fcc-3e7d-4336-a7b2-2ab1225e6941')
[cds] - POST /-/cds/model-provider/getCsn
[cds] - POST /-/cds/model-provider/getCsn
[cds] - POST /-/cds/model-provider/getCsn
[cds] - POST /-/cds/model-provider/getCsn
[cds] - POST /-/cds/model-provider/getCsn
[cds] - POST /-/cds/model-provider/getCsn
[cds] - POST /-/cds/model-provider/getCsn
[cds] - POST /-/cds/model-provider/getCsn
[cds] - POST /-/cds/model-provider/getCsn
[cds] - POST /-/cds/model-provider/getCsn
[cds] - POST /-/cds/model-provider/getCsn
[cds] - POST /-/cds/model-provider/getCsn
[cds] - POST /-/cds/model-provider/getCsn
[cds] - POST /-/cds/model-provider/getCsn
[cds] - POST /-/cds/model-provider/getCsn
[cds] - POST /-/cds/model-provider/getCsn
[cds] - POST /-/cds/model-provider/getCsn

**Comment by SummerLatte** [comment]
Hi
The same error happen to me too.
I change the log level to debug and following is my log.

  Migrating libraries... ok  (0s 11ms)
  Making... 
   Preparing... 
   Preparing the make transaction... 
   Preparing the make transaction... ok  (0s 26ms)

[deploy] -    Deploying the configuration file "src/gen/._.hdiconfig"... 
   Error: "src/gen/._.hdiconfig": the name of a configuration file must consist of the file ".hdiconfig" only [8211533]
   Error: Deploying the configuration file "src/gen/._.hdiconfig"... failed [8211678]
   Error: "src/gen/._.hdiconfig": could not process the configuration file [8211713]

[deploy] -      at "src/gen/._.hdiconfig" (0:0)
   Error: Preparing... failed [8211602]
   Make failed (5 errors, 0 warnings): tried to deploy 216 files, undeploy 0 files, redeploy 0 dependent files 
  Error: Making... failed [8211605]
 Error: Starting make in the container "7C3B00A0D66B4D7A8A036767AEC49FE7" with 216 files to deploy, 0 files to undeploy... failed [8214168]

[deploy] - Deployment to container 7C3B00A0D66B4D7A8A036767AEC49FE7 failed - error: HDI make failed [Deployment ID: none].

[deploy] - Deployment ended at 2023-05-31 09:08:42

[deploy] - Error: HDI make failed

[deploy] - (4s 438ms)

[deploy] - 

[mtx] - -------------[END HDI-DEPLOY-OUTPUT]----------------
[mtx] - Error: HDI deployment failed with exit code 1
    at /layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/bin/deploy/to-hana/hdiDeployUtil.js:142:35
    at ChildProcess.<anonymous> (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/hdi-deploy/library.js:102:14)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
    at Process.callbackTrampoline (node:internal/async_hooks:130:17)
[cds] - User "sb-xsuaa-standard-java!t6650" request URL /pollJob(ID='6ebd0517-4705-4e74-98e9-3319f25f5aa7')

Thanks & Regards.

**Comment by beckermarc** [comment]
> [deploy] - Deploying the configuration file "src/gen/..hdiconfig"...
> Error: "src/gen/..hdiconfig": the name of a configuration file must consist of the file ".hdiconfig" only [8211533]
> Error: Deploying the configuration file "src/gen/..hdiconfig"... failed [8211678]
> Error: "src/gen/..hdiconfig": could not process the configuration file [8211713]

This seems to be a different error. Can you please check if such a `..hdiconfig` file is available locally after building the application using `cds build --production` in your `db/gen` folder?

**Comment by SummerLatte** [comment]
HI
It's solved by following this https://github.tools.sap/cap/issues/issues/13073
It's related to OS when cds build generate .hdiconfig. Some versions of MacOS seems will add some prefix in filename. Could use export COPYFILE_DISABLE=1 to disable this feature.

Thanks & Regards.
