### ISSUE TITLE
Subscription handler not worked when deploy the application on k8s

### ISSUE THREAD

**Issue by JocelynGu135** [SAP-samples/cloud-cap-samples-java#241]
Dear colleague,

In java project, contains subscription handler. After subscribe will send audit log security message to provider tenant.
https://github.com/SAP-samples/cloud-cap-samples-java/blob/main/srv/src/main/java/my/bookshop/handlers/SubscriptionHandler.java

Did you know how to check this log to ensure the afterSubscribe execute successfully?

Because I add more logic in subscription handler. eg: get dependencies.  The code is work successfully in cf environment. But when I deploy in k8s, this is not working successfully.
https://github.tools.sap/erp4sme/job-worker-app-java/blob/main/srv/src/main/java/my/bookshop/handlers/SubscriptionHandler.java

Best Regards
Jocelyn

**Comment by beckermarc** [comment]
> Did you know how to check this log to ensure the afterSubscribe execute successfully?

In our sample the log line is just written to the application logs via STDOUT.

> But when I deploy in k8s, this is not working successfully.

I think it is better to discuss this in an internal support ticket.
