### ISSUE TITLE
Loading data on preview with mock user ends with `401`

### ISSUE THREAD

**Issue by johannes-kolbe** [SAP-samples/cloud-cap-samples-java#256]
Hi,

After generating a sample app on the provided cloud cap samples service (e.g. `authors`) and starting a preview via `mvn spring-boot:run`, we are running into authorisation issues with the loading of data. 

This is mostly reproducible on a Incognito window, or on testing pipeline (constantly): `$batch failed - Error: Communication error: 401 error`. Now the error message is even more explicit.

Can you assist us in how to address this issue?

- Used generator: `@sap/generator-fiori` on https://www.npmjs.com/package/@sap/generator-fiori
- Service: `CatalogService`
- Entity: `Authors`
- Mock user (to browse books): https://github.com/SAP-samples/cloud-cap-samples-java/#building-and-running

![Screenshot 2023-10-19 at 15 13 16](https://github.com/SAP-samples/cloud-cap-samples-java/assets/106824015/40f49ffa-d17d-4c4e-8522-6f8011433473)

**Comment by beckermarc** [comment]
Do you serve the UI resources through the Java application or do you start it separately (on a different port) from a dedicated app that serves the UI resources only?

If you use the later approach you will need to configure basic auth credentials for a mock user with the dedicated app, usually where you also configure the backend endpoint.

**Comment by johannes-kolbe** [comment]
Hi @beckermarc,
thanks for the description and code example. In this case we do rely on the Java application for preview (`mvn spring-boot:run`), and also get an auth popup. But after entering user credentials, this then returns 401 in certain cases.

If it helps, the generated app is `authors`: [cloud-cap-samples-java-2023-10-201404.zip](https://github.com/SAP-samples/cloud-cap-samples-java/files/13055080/cloud-cap-samples-java-2023-10-201404.zip) and is started via `http://localhost:8080/authors/webapp/index.html` after mvn run.

I hope I am not overseeing sth obvious that is hindering the auth enablement.

**Comment by beckermarc** [comment]
Where and when do you see these 401 responses? I just tried out your zip locally and was able to serve the Authors UI perfectly fine. I was able to browse authors, their books and even add reviews for the books.

**Comment by johannes-kolbe** [comment]
Since `initialLoad` is enabled for the app, I see them immediately on opening the List Report page.
1. Open new icognito browser (Chrome/Arc)
2. Clear cache and cookies of browser (asks to close all windows)
3. Open browser window again, go to Url
4. Fill out User popup, then 401 error window is displayed immediately after
5. Without `initialLoad`, the error is displayed on pressing the `Go` button on LR page

**Comment by beckermarc** [comment]
Looks like Chromium based browsers avoid setting the `Authorization` header on all parent paths of the path where the initial basic login happened. For example:
- `/authors/webapp/index.html` triggers the Basic authentication
- `/authors/webapp/i18n/i18n.properties gets the `Authorization` header
- `/api/browse/$batch` doesn't get an `Authorization` header.

After opening an endpoint that requires authentication on a parent path explicitly in the browser the propagation is broadened, e.g. after opening `/fiori.html` all endpoints above get the `Authorization` header.

The behaviour isn't reproducible in Firefox, but only in Chrome and Edge.

**Comment by johannes-kolbe** [comment]
Thanks @beckermarc, found a workaround to address the symptom, closing issue.
