### ISSUE TITLE
Steps defined for Single Tenant deployment for Kyma doesn't work

### ISSUE THREAD

**Issue by robin-carry** [SAP-samples/cloud-cap-samples-java#259]
Currently if we follow the steps as defined in the `README.md`, on running the command `cds add helm` the generated `values.yaml` results in having `sidecar` (aka with respect to multi-tenant application) entry.

Without much deep understanding, did the following change to get it working:

1. Removed the `profile` = `with-mtx-sidecard`

```yaml
     "profiles": [
-        "with-mtx-sidecar",
         "java"
     ]
``` 

2. Deleted the `mtx` folder (`mtx/sidecar/package.json`)

--
To follow the steps, deploy first in CF Trial landscape and then follow steps for single tenant and deploy in BTP Kyma Trial landscape.

**Comment by beckermarc** [comment]
Thanks for raising that. But you followed the replacement instructions for the `requires` section in `.cdsrc.json` here: https://github.com/SAP-samples/cloud-cap-samples-java#add-deployment-files correct?

I think you are right, that this instruction misses to add the hint to remove the `with-mtx-sidecar` profile from the `profiles` section in `.cdsrc.json`.

**Comment by beckermarc** [comment]
I added `documentation` and `enhancement` labels. Currently it works as designed, but we will revisit that and reiterate on that. Until that we can improve the documentation with the currently required steps already -> 

> Where do I ask questions about these tutorials?

From CAP perspective you can check our documentation about this here: https://cap.cloud.sap/docs/resources/
Questions can be answered in the CAP space on answers.sap.com: https://answers.sap.com/tags/9f13aee1-834c-4105-8e43-ee442775e5ce. You can also ask Kyma deployment related questions there: https://answers.sap.com/tags/73554900100800003012
