### ISSUE TITLE
Max Depth Exceeded : When building docker image of `bookshop-srv`

### ISSUE THREAD

**Issue by robin-carry** [SAP-samples/cloud-cap-samples-java#284]
In the the [build step](https://github.com/SAP-samples/cloud-cap-samples-java?tab=readme-ov-file#build), when we are running command to build the `bookshop-srv` docker image, we get error.

### Error 

`ERROR: failed to build: failed to write image to the following tags: [pack.local/builder/75677762716b6764666c:latest: loading image "pack.local/builder/75677762716b6764666c:latest". first error: embedded daemon response: max depth exceeded]`

### Command with Issue

```shell
pack build $YOUR_CONTAINER_REGISTRY/bookshop-srv \
        --path srv/target/*-exec.jar \
        --buildpack gcr.io/paketo-buildpacks/sap-machine \
        --buildpack gcr.io/paketo-buildpacks/java \
        --builder paketobuildpacks/builder:base \
        --env SPRING_PROFILES_ACTIVE=cloud \
        --env BP_JVM_VERSION=17
```

### Temporary work-around

Currently the fix to get over the above issue is to use specific version of the `buildpack` docker images. 

```shell
pack build $CONTAINER_REGISTRY/bookshop-srv \
        --path srv/target/*-exec.jar \
        --buildpack gcr.io/paketo-buildpacks/sap-machine:10.2.8 \
        --buildpack gcr.io/paketo-buildpacks/java:10.0.0 \
        --builder paketobuildpacks/builder:base \
        --env SPRING_PROFILES_ACTIVE=cloud \
        --env BP_JVM_VERSION=17
```

**Comment by beckermarc** [comment]
Can you try with `--builder paketobuildpacks/builder-jammy-base` (without fixed buildpack docker versions)? The `--builder paketobuildpacks/builder:base` is [deprecated](https://github.com/paketo-buildpacks/base-builder).

**Comment by abhianuj10** [comment]
This works, Thanks @beckermarc
