### ISSUE TITLE
The remote OData service responded with status code 401' Error After Deployment on SAP BTP

### ISSUE THREAD

**Issue by fenrir-liutiecheng** [SAP-samples/cloud-cap-samples-java#319]
Under the "shipping" section, when clicking the "Start" button for both "Manage Notes" and "Show Shipping Address", the error "The remote OData service responded with status code '401'" is displayed. No other screens, including the management screen, are showing up. This error does not occur locally, but only when deployed to SAP BTP. How can this problem be resolved?

![image](https://github.com/SAP-samples/cloud-cap-samples-java/assets/57246526/1e05972c-e45f-4940-a6b8-2efd5ff6cc98)

**Comment by beckermarc** [comment]
When deploying to the cloud the sandbox profile is activated: https://github.com/SAP-samples/cloud-cap-samples-java/blob/main/mta-multi-tenant.yaml#L18

When the sandbox profile is activated the data is tried to be fetched from api.sap.com, which requires an API Key, as described in the README: https://github.com/SAP-samples/cloud-cap-samples-java?tab=readme-ov-file#api_business_partner-remote-service-and-spring-profiles

You either need to provide the APIKey or remove the sandbox profile from the active profiles for the cloud deployment.

**Comment by fenrir-liutiecheng** [comment]
Where do I set the CDS_REMOTE_SERVICES_API_BUSINESS_PARTNER_HTTP_HEADERS_APIKEY? I tried the following tutorial but it was unsuccessful.
https://developers.sap.com/tutorials/btp-app-ext-service-add-consumption.html
In addition, after removing the sandbox and redeploying to SAP BTP, another error occurred when clicking the link.
I apologize, as I am a newcomer to SAP BTP, and I would appreciate any guidance you can provide.

**Comment by beckermarc** [comment]
> Where do I set the CDS_REMOTE_SERVICES_API_BUSINESS_PARTNER_HTTP_HEADERS_APIKEY?

You can either set it directly in application.yaml, before deploying: https://github.com/SAP-samples/cloud-cap-samples-java/blob/main/srv/src/main/resources/application.yaml#L66
Or set `CDS_REMOTE_SERVICES_API_BUSINESS_PARTNER_HTTP_HEADERS_APIKEY` with the value of the API Key as environment variable on the deployed application in BTP (using `cf set-env`)

> another error occurred when clicking the link.

What kind of error?

**Comment by fenrir-liutiecheng** [comment]
@beckermarc 

> You can either set it directly in application.yaml...

Thank you very much, the problem has been solved after setting it up this way!

After I removed the sandbox and redeployed to SAP BTP, the following error occurred:
![image](https://github.com/SAP-samples/cloud-cap-samples-java/assets/57246526/3ec4a951-cf11-428c-83f6-3a4a9a39c3eb)
![image](https://github.com/SAP-samples/cloud-cap-samples-java/assets/57246526/9916ed5d-86d5-4ca7-9d73-18ee48525114)

**Comment by beckermarc** [comment]
> Thank you very much, the problem has been solved after setting it up this way!

Great!

> After I removed the sandbox and redeployed to SAP BTP, the following error occurred:

Ah yeah I forgot that this setup would require additional steps. The mocked tables for the remote entities are not available in a cloud deployment, which is why the sandbox profile is mandatory for cloud deployment.

**Comment by beckermarc** [comment]
I also tried to improve the docs in the README: https://github.com/SAP-samples/cloud-cap-samples-java/pull/322
