### ISSUE TITLE
Code tour broken: Comments shown without source code.

### ISSUE THREAD

**Issue by AHaury** [SAP-samples/cloud-cap-samples-java#332]
Hello,
The codetour seems to be broken, When navigating it, the comments are shown alright. But the source code is not shown. Only the bread crumbs of the file are displayed at the very top of the code tour tab: cf. attached screen copy. Navigation from the bread crumb to the source code file is not possible either. Per consequence, one has to (1) switch from the code tour player to the source code explorer and (2) open the file manually in a second window which is a bit cumbersome. Could you please clarify whether this is the intended behavior of the code tour? (From what can find on the web about code tours, the comments are supposed to be shown embedded in the source code.)
Many thanks and best regards,
Axel.

![2024-06-12_16-17-20](https://github.com/SAP-samples/cloud-cap-samples-java/assets/67156037/18ca624c-3578-4b4a-8108-ac0a4e7fd3cd)

**Comment by beckermarc** [comment]
Thanks for reporting, will be fixed with: https://github.com/SAP-samples/cloud-cap-samples-java/pull/333
