### ISSUE TITLE
Most the API's are failing 

### ISSUE THREAD

**Issue by vikalpsareen** [SAP-samples/cloud-cap-samples-java#8]
I have taken the latest code and followed the steps as suggested in readme file.API's are failing with below error :

Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: CATALOGSERVICE_BOOKS)

That's an example for one API call. But it's happening for all the API's call. Do I need to make some changes to make it work?

I am using sqlite profile.

**Comment by beckermarc** [comment]
It looks like the file-based SQLite database is not found correctly. Have you created it using `cds deploy`? 

Depending how you start the application the working directory might be calculated differently and therefore the default path in the application.yaml might be incorrect. You could try to fully qualify the path to the file-based sqlite database in application.yaml: https://github.com/SAP-samples/cloud-cap-samples-java/blob/master/srv/src/main/resources/application.yaml#L22

You can also try out the default profile, which initializes an in-memory database for you and also loads all CSV files into that automatically.

**Comment by vikalpsareen** [comment]
Thanks that worked
