### ISSUE TITLE
How to deploy to SCP(cloud foundry)?

### ISSUE THREAD

**Issue by trulliandloeb** [SAP-samples/cloud-cap-samples-java#9]
Dear,

How to deploy this sample to SCP cloud foundry with HANA?
I've checked https://cap.cloud.sap/docs/advanced/deploy-to-cloud but seems it didn't help.

**Comment by zhangyaya** [comment]
You can refer to this doc https://developers.sap.com/tutorials/cp-cap-java-deploy-cf.html.
I deployed the sample to SCP successfully.

**Comment by iwonahahn** [comment]
@zhangyaya thanks for the link to the tutorial how to do this for Java.
@trulliandloeb for Node.js you can also refer to the mission here https://developers.sap.com/mission.cp-starter-extensions-cap.html. The second tutorial is about deploying to SAP Cloud Platform.

Best regards,
Iwona
